---
- name: Create registry sources directory under {{ registry_dir }}
  file: state=directory path={{ registry_dir }}

  #- name: Create certs directory under {{ registry_dir }}
  #  file: state=directory path={{ registry_dir }}/certs
  #
  #- name: Create self signed certificate
  #  shell: openssl req -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=domain.com" -keyout {{ registry_dir }}/certs/domain.key -out {{ registry_dir }}/certs/domain.crt

- name: Check if namespace {{ registry_namespace }} already exists
  shell: kubectl get namespace {{ registry_namespace }} || true
  register: namespace_status 
  changed_when: false
  become: true

- name: Create {{ registry_namespace }} namespace
  command: kubectl create namespace {{ registry_namespace }}
  become: true
  when:  "'registry' not in namespace_status.stdout" 

- name: Template kubernetes template to {{ registry_dir }}
  template:
    src: ../templates/registry.yaml
    dest: "{{ registry_dir }}/registry.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Deploy registry pod and service
  command: kubectl apply -f "{{ registry_dir }}/registry.yaml"
  become: true

- name: Check for running status of pod
  command: kubectl get pod --namespace={{ registry_namespace }}
  register: registry_pod_status
  until: "'registry' and 'Running' in registry_pod_status.stdout"
  delay: 5
  retries: 10
  become: true

- name: Get cluster ip of registry service
  shell: kubectl get service registry --namespace={{ registry_namespace }} | awk '{ print $3 }' | grep -v CLUSTER-IP
  register: registry_ip_result
  become: true

- name: Show cluster ip
  debug:
    var: registry_ip_result.stdout

- name: Add daemon.json to /etc/docker
  template:
    src: ../templates/daemon.j2
    dest: /etc/docker/daemon.json
    mode: 0600
  become: true
  notify:
     - reload daemon
     - restart docker
