---
- name: Install list of packages needed for docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  become: true
